/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author david
 * 
 */

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import utils.ConstUtil;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class hitungipk extends javax.swing.JFrame {
        
Connection con;
PreparedStatement pre, index;
Statement perintah;
DefaultTableModel model = new DefaultTableModel();

//        private final String NamaKolom[] = {"NIM", "Nama", "Semester", "IPS"};
//        private int jumBaris = 0;
//        private int jumKolom = 4;
//        private String DataTabel[][] = new String
//        [jumBaris][jumKolom];
//        private DefaultTableModel model = new 
//        DefaultTableModel (DataTabel,NamaKolom);
//        private  int bariske = 0;
    /**
     * Creates new form p3Welcome
     */
    public hitungipk() {
        model.addColumn("NIM");
        model.addColumn("Semester");
        model.addColumn("IPS");
//        model.addColumn("ips");
    try {
        this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_w12?user=root&password=Vincen32168");
    } catch (SQLException ex) {
        Logger.getLogger(hitungipk.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        this.perintah = con.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(hitungipk.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
 this.setTitle("StudIP");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ICON/logo.png")));
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JButton();
        btndatauser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        hasilipk = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdate.setBackground(new java.awt.Color(252, 97, 77));
        btnupdate.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnupdate.setText("Data User");
        btnupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 200, 34));

        btndatauser.setBackground(new java.awt.Color(252, 97, 77));
        btndatauser.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btndatauser.setText(" Hitung IPS");
        btndatauser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btndatauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatauserActionPerformed(evt);
            }
        });
        jPanel3.add(btndatauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 200, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("StudIP");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("More fast to Calculate");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        jTable2.setBackground(new java.awt.Color(235, 236, 230));
        jTable2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Semester", "IPS"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 170));

        lblName.setBackground(new java.awt.Color(255, 153, 51));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblName.setText("{NAME AUTH}");
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 60, 20));

        hasilipk.setBackground(new java.awt.Color(235, 236, 230));
        hasilipk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hasilipk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilipk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilipkActionPerformed(evt);
            }
        });
        jPanel3.add(hasilipk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 150, 20));

        btnkeluar.setBackground(new java.awt.Color(252, 97, 77));
        btnkeluar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 97, 77)));
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel3.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 70, 30));

        jButton1.setBackground(new java.awt.Color(252, 97, 77));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("Hitung IPK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setText("IPK Mahasiswa :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-person-34.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-calculator-50.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jButton2.setBackground(new java.awt.Color(235, 236, 230));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("Hapus data Ips");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 130, -1));

        jLabel2.setBackground(new java.awt.Color(252, 97, 77));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/q982rqr.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(734, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
//            pretab = con.prepareStatement();
            String ganteng1[] = new String[3];
            
            String sql = String.format("select * from dataipk where nim = '%s' ", ConstUtil.auth.getNim());
            ResultSet rs = perintah.executeQuery(sql);
            while (rs.next()) {
                ganteng1[0] = rs.getString("nim");
                ganteng1[1] = String.valueOf(rs.getInt("semesterhitung"));
                ganteng1[2] = String.valueOf(rs.getDouble("ips"));
                
                model.addRow(ganteng1);
                jTable2.setModel(model);
            }

            
        }catch(SQLException e){
            e.printStackTrace();
//            System.out.println("Error We");
        };
        lblName.setText(ConstUtil.auth.getName());
             
    }//GEN-LAST:event_formWindowOpened

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        new datauser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndatauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatauserActionPerformed

        new hitungips().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btndatauserActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
//        ConstUtil.auth= null;
        new TampilanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double hasil = 0.0;
        Double totalSks = 0.0;
        int cekada = 0;
        double ips;           
      
        try{
            String querycek = String.format("select COUNT(1) from dataipk where nim = '%s'", ConstUtil.auth.getNim());
        ResultSet cek = perintah.executeQuery(querycek);
        while (cek.next()){
            cekada = Integer.parseInt(cek.getString(1));
        }
        if (cekada != 0){
             try {    
        String query = String.format("select AVG (ips) from dataipk where nim = '%s'", ConstUtil.auth.getNim());
        ResultSet rs = perintah.executeQuery(query);
        while(rs.next()){
        hasilipk.setText(String.format("%.2f", Double.parseDouble(rs.getString(1)) ));
        }
            } catch (SQLException ex) {
            Logger.getLogger(hitungips.class.getName()).log(Level.SEVERE, null, ex);
//        JOptionPane.showMessageDialog(null, "Data berhasil dihapus! Silahkan Refresh!", "Data Updated", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (cekada == 0){
            JOptionPane.showMessageDialog(null, "Tabel harus diisi, hitung IPS dahulu!", "Data Updated", JOptionPane.INFORMATION_MESSAGE);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
//        try {    
//        String query = String.format("select AVG (ips) from dataipk where nim = '%s'", ConstUtil.auth.getNim());
//        ResultSet rs = perintah.executeQuery(query);
//        while(rs.next()){
//        hasilipk.setText(String.format("%.2f", Double.parseDouble(rs.getString(1)) ));
//        }
//            } catch (SQLException ex) {
//            Logger.getLogger(hitungips.class.getName()).log(Level.SEVERE, null, ex);
////        JOptionPane.showMessageDialog(null, "Data berhasil dihapus! Silahkan Refresh!", "Data Updated", JOptionPane.INFORMATION_MESSAGE);
//            }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void hasilipkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilipkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilipkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Hapus().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed
    private void tampilkan1(){
 
         try{
           
//            pretab = con.prepareStatement();
            String ganteng1[] = new String[3];
            
            String sql = String.format("select * from dataipk where nim = '%s", ConstUtil.auth.getNim());
            ResultSet rs = perintah.executeQuery(sql);
            while (rs.next()) {
                ganteng1[0] = rs.getString("nim");
                ganteng1[1] = String.valueOf(rs.getInt("semesterhitung"));
                ganteng1[2] = String.valueOf(rs.getDouble("ips"));
                
                model.addRow(ganteng1);
                jTable2.setModel(model);
            }

            
        }catch(SQLException e){
            e.printStackTrace();
//            System.out.println("Error We");
        };
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitungipk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitungipk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitungipk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitungipk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitungipk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndatauser;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnupdate;
    private javax.swing.JTextField hasilipk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
