/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utils.ConstUtil;
import models.User;
import models.datapengguna;
import models.dataipk;
import net.proteanit.sql.DbUtils;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
//import models.User;
import utils.ConstUtil;
public class hitungips extends javax.swing.JFrame {

Connection con;
PreparedStatement pre, pretab,preres;
Statement perintah;
DefaultTableModel model = new DefaultTableModel();

Double[] array = {999.0, 999.0, 999.0, 999.0, 999.0, 999.0, 999.0, 999.0};
Double[] arraySks = {999.0, 999.0, 999.0, 999.0, 999.0, 999.0, 999.0, 999.0};

public double konversi(String input){
        
        switch (input.toLowerCase()) {
            case "a" -> {
                return 4.0;
        }
                
            case "ab" -> {
                return 3.5;
        }
                
            case "b" -> {
                return 3.0;
        }
                
            case "bc" -> {
                return 2.5;
        }
                    
            case "c" -> {
                return 2.0;
        }
                
            case "d" -> {
                return 1.0;
        }
                
            default -> {
                return 0;
        }
        }
    }

public double inputan(String input1){
//        int input1 = Integer.parseInt(in);
        switch (input1) {
            case "1" -> {
                return 1.0;
        }
                
            case "2" -> {
                return 2.0;
        }
                
            case "3" -> {
                return 3.0;
        }
                
            case "4" -> {
                return 4.0;
            }
            default -> {
                return 0;
        }
        }
    }

    /**
     * Creates new form DataUser
     */
    public hitungips() {
        model.addColumn("NIM");
        model.addColumn("Semester");
        model.addColumn("Mata Kuliah");
        model.addColumn("Banyak SKS");
        model.addColumn("Nilai");
//        model.addColumn("ips");
    try {
        this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_w12?user=root&password=Vincen32168");
    } catch (SQLException ex) {
        Logger.getLogger(hitungips.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        this.perintah = con.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(hitungips.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
         this.setTitle("StudIP");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ICON/logo.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsemesterdihitung = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtips = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttotalsks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Kirim = new javax.swing.JButton();
        txtbobot1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsks1 = new javax.swing.JComboBox<>();
        txtsemester = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtmatakuliah1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(720, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(252, 97, 77));
        jButton3.setText("Simpan IPS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 92, 40));

        jButton1.setBackground(new java.awt.Color(252, 97, 77));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("Menu Utama");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 97, 77)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 110, 30));

        txtsemesterdihitung.setBackground(new java.awt.Color(252, 97, 77));
        txtsemesterdihitung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        txtsemesterdihitung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtsemesterdihitung.setMaximumSize(new java.awt.Dimension(720, 490));
        txtsemesterdihitung.setMinimumSize(new java.awt.Dimension(720, 490));
        jPanel1.add(txtsemesterdihitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("semester yang akan dihitung");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hasil Perhitungan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 109, -1));

        txtips.setBackground(new java.awt.Color(235, 236, 230));
        txtips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipsActionPerformed(evt);
            }
        });
        jPanel1.add(txtips, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("IPS ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        txttotalsks.setBackground(new java.awt.Color(235, 236, 230));
        txttotalsks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txttotalsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalsksActionPerformed(evt);
            }
        });
        jPanel1.add(txttotalsks, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Total SKS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 60, 20));

        jButton2.setBackground(new java.awt.Color(252, 97, 77));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("Hitung IPS");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 99, 50));

        jTable1.setBackground(new java.awt.Color(235, 236, 230));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Semester", "Mata Kuliah", "Bobot"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, 205));

        Kirim.setBackground(new java.awt.Color(252, 97, 77));
        Kirim.setText("Kirim");
        Kirim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirimActionPerformed(evt);
            }
        });
        jPanel1.add(Kirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 80, 50));

        txtbobot1.setBackground(new java.awt.Color(235, 236, 230));
        txtbobot1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "B", "BC", "C", "D", "E" }));
        txtbobot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel1.add(txtbobot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 100, 24));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Semester");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Banyak SKS ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Grade");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtsks1.setBackground(new java.awt.Color(235, 236, 230));
        txtsks1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        txtsks1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        txtsks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsks1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtsks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 100, 24));

        txtsemester.setBackground(new java.awt.Color(235, 236, 230));
        txtsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        txtsemester.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel1.add(txtsemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, 24));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Mata Kuliah ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jButton4.setBackground(new java.awt.Color(235, 236, 230));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setText("Hapus data");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, 20));

        txtmatakuliah1.setBackground(new java.awt.Color(235, 236, 230));
        txtmatakuliah1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        txtmatakuliah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatakuliah1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtmatakuliah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 131, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Perhitungan IPS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 30));

        jLabel4.setBackground(new java.awt.Color(235, 236, 230));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/q982rqr.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(734, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    tampilkan();
//    tampilkan1();
    }//GEN-LAST:event_formWindowOpened

    private void KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirimActionPerformed
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_w12?user=root&password=Vincen32168");
            pre = con.prepareStatement("INSERT INTO datapengguna (nim,matakuliah1,sks1,bobot1,semester) VALUES (?,?,?,?,?)");
            pre.setString(1, ConstUtil.auth.getNim());
            pre.setString(2,txtmatakuliah1.getText());
            pre.setString(3, (String) txtsks1.getSelectedItem());
            pre.setString(4, (String) txtbobot1.getSelectedItem());
            pre.setString(5, (String) txtsemester.getSelectedItem());
            pre.executeUpdate();
            tampilkan();
        }catch(SQLException e){
            e.printStackTrace();
//            System.out.println("Error We");
        };
        
        this.dispose();
        new hitungips().setVisible(true);
    }//GEN-LAST:event_KirimActionPerformed

    private void txtmatakuliah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatakuliah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatakuliah1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Double hasil = 0.0;
        Double totalSks = 0.0;
        double ips;
    
                
    try {
        String query = String.format("select * from datapengguna Where nim  = '%s'", ConstUtil.auth.getNim());
        
        ResultSet rs = perintah.executeQuery(query);

        while(rs.next()){
            if(rs.getString("semester").equals(txtsemesterdihitung.getSelectedItem())){
                hasil += konversi(rs.getString("bobot1")) * Double.parseDouble(rs.getString("sks1"));
                totalSks += Double.parseDouble(rs.getString("sks1"));
                
                array[Integer.parseInt((String) txtsemesterdihitung.getSelectedItem()) - 1] = hasil;
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(hitungips.class.getName()).log(Level.SEVERE, null, ex);
    }

    hasil = hasil / totalSks;
    

    txttotalsks.setText(String.format("%.2f", totalSks));
    txtips.setText(String.format("%.2f", hasil));
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void txtipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new hitungipk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_w12?user=root&password=Vincen32168");
            pre = con.prepareStatement("INSERT INTO dataipk (nim,semesterhitung,ips) VALUES (?,?,?) ");
            pre.setString(1, ConstUtil.auth.getNim());
            pre.setString(2, (String) txtsemesterdihitung.getSelectedItem());
            pre.setString(3, txtips.getText());
            pre.executeUpdate();
//            tampilkan1();
        }catch(SQLException e){
            e.printStackTrace();
//            System.out.println("Error We");
        };
        
        this.dispose();
        new hitungipk().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttotalsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalsksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalsksActionPerformed

    private void txtsks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsks1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

            new Hapus1().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void tampilkan(){
 
         try{
           
//            pretab = con.prepareStatement();
            String ganteng[] = new String[6];
//            String nim = ConstUtil.auth.getNim();
            String sql = String.format("select * from datapengguna where nim = '%s'", ConstUtil.auth.getNim());
            
            ResultSet rs = perintah.executeQuery(sql);
            while (rs.next()) {
                ganteng[0] = rs.getString("nim");
                ganteng[1] = String.valueOf(rs.getInt("semester"));
                ganteng[2] = rs.getString("matakuliah1");
                ganteng[3] = String.valueOf(inputan(rs.getString("sks1")));
                ganteng[4] = String.valueOf(konversi( rs.getString("bobot1")));
//                ganteng[5] = rs.getString("ips");
                ganteng[5] = String.valueOf(rs.getDate("created_at"));
                
                model.addRow(ganteng);
                jTable1.setModel(model);

            }
            
            
            
        }catch(SQLException e){
            e.printStackTrace();
//            System.out.println("Error We");
        };
    }
    
//        private void tampilkan1(){
// 
////         try{
////           
//////            pretab = con.prepareStatement();
////            String ganteng1[] = new String[3];
////            
////            String sql = String.format("select * from dataipk");
////            ResultSet rs = perintah.executeQuery(sql);
////            while (rs.next()) {
////                ganteng1[0] = rs.getString("nim");
////                ganteng1[1] = String.valueOf(rs.getInt("semesterhitung"));
////                ganteng1[2] = String.valueOf(rs.getString("ips"));
////                
////                model.addRow(ganteng1);
////                jTable2.setModel(model);
////            }
////
////            
////        }catch(SQLException e){
////            e.printStackTrace();
//////            System.out.println("Error We");
////        };
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitungips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitungips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitungips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitungips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitungips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kirim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> txtbobot1;
    private javax.swing.JTextField txtips;
    private javax.swing.JTextField txtmatakuliah1;
    private javax.swing.JComboBox<String> txtsemester;
    private javax.swing.JComboBox<String> txtsemesterdihitung;
    private javax.swing.JComboBox<String> txtsks1;
    private javax.swing.JTextField txttotalsks;
    // End of variables declaration//GEN-END:variables
//
//    private static class hitungipk {
//        
//        Connection con;
//        PreparedStatement pre, pretab,preres;
//        Statement perintah;
//        DefaultTableModel model = new DefaultTableModel();
//        public hitungipk() {
//        model.addColumn("NIM");
//        model.addColumn("Semester");
//        model.addColumn("Nilai");
////        model.addColumn("ips");
//    try {
//        this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_w12?user=root&password=Vincen32168");
//    } catch (SQLException ex) {
//        Logger.getLogger(hitungipk.class.getName()).log(Level.SEVERE, null, ex);
//    }
//    try {
//        this.perintah = con.createStatement();
//    } catch (SQLException ex) {
//        Logger.getLogger(hitungipk.class.getName()).log(Level.SEVERE, null, ex);
//    }
////        initComponents();
//    }
//
//        private void setVisible(boolean b) {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        }
//    
//    }
}
